package ArpCLI::OpenAPI::Manuals;

use strict;
use warnings;

use File::Basename qw(dirname);
use File::Path qw(make_path);

sub new {
    my ($class, %args) = @_;
    return bless {
        root    => $args{root} // 'manuals',
        parsed  => $args{parsed},
        map     => $args{map},
    }, $class;
}

sub write_all {
    my ($self) = @_;
    my @written;
    my %writers = (
        'endpoints'    => 'endpoints',
        'errors'       => 'errors',
        'schemas'      => 'schemas',
        'api-overview' => 'api_overview',
    );
    while (my ($file, $method) = each %writers) {
        my $path = "$self->{root}/$file.md";
        _write_file($path, $self->$method());
        push @written, $path;
    }
    return \@written;
}

sub _banner {
    return "<!-- AUTO-GENERATED by script/sync-openapi - do not edit by hand -->\n\n";
}

sub endpoints {
    my ($self) = @_;
    my $map  = $self->{map};
    my @read;
    my @write;
    for my $id (sort keys %$map) {
        my $row = $map->{$id};
        next unless $row->{path} && $row->{http_method};
        my $line = sprintf(
            '| `%s %s` | %s | `%s` | %s |',
            $row->{http_method},
            $row->{path},
            $row->{module} // 'UNKNOWN',
            $row->{method} // 'unknown',
            $row->{scope} // '-',
        );
        if (uc($row->{http_method}) eq 'GET') {
            push @read, $line;
        }
        else {
            push @write, $line;
        }
    }

    my $body = _banner();
    $body .= "# Endpoints\n\n";
    $body .= "All paths are under `/api/v1/`. Module mapping in `lib/ArpCLI/API/`.\n\n";
    $body .= "## Read (GET)\n\n";
    $body .= "| HTTP | Module | Method | Scope |\n";
    $body .= "|------|--------|--------|-------|\n";
    $body .= join("\n", @read) . "\n\n" if @read;
    $body .= "## Write (non-GET)\n\n";
    $body .= "| HTTP | Module | Method | Scope |\n";
    $body .= "|------|--------|--------|-------|\n";
    $body .= join("\n", @write) . "\n\n" if @write;

    my $range = $self->_bandwidth_ranges;
    if (@$range) {
        $body .= "## Bandwidth `range` values\n\n";
        $body .= join(', ', map { "`$_`" } @$range);
        $body .= " (default `30d`)\n";
    }
    return $body;
}

sub errors {
    my ($self) = @_;
    my $types = $self->{parsed}{error_types} // [];
    my $body = _banner();
    $body .= "# Errors\n\n";
    $body .= "JSON shape:\n\n";
    $body .= "```json\n{ \"error\": { \"type\": \"...\", \"message\": \"...\" } }\n```\n\n";
    $body .= "## `error.type` values\n\n";
    $body .= join(', ', @$types) . "\n\n" if @$types;
    $body .= "## HTTP status mapping\n\n";
    $body .= "| Status | Typical type |\n";
    $body .= "|--------|----------------|\n";
    $body .= "| 401 | unauthorized |\n";
    $body .= "| 403 | insufficient_scope / forbidden |\n";
    $body .= "| 404 | not_found |\n";
    $body .= "| 402 | payment_method_required |\n";
    $body .= "| 422 | unprocessable |\n";
    $body .= "| 429 | rate_limited |\n";
    $body .= "| 502 | dispatch_failed |\n\n";
    $body .= "Client: `ArpCLI::HTTP` throws `ArpCLI::Error` with `type`, `message`, `status`, `body`.\n";
    return $body;
}

sub schemas {
    my ($self) = @_;
    my $schemas = $self->{parsed}{schemas} // {};
    my @priority = qw(Server ServerBilling Bandwidth DnsRecord Plan OsTemplatesList Pagination);
    my %seen;
    my @order = (grep { exists $schemas->{$_} } @priority);
    push @order, sort grep { !$seen{$_}++ } keys %$schemas;

    my $body = _banner();
    $body .= "# Key schemas\n\n";
    for my $name (@order) {
        my $s = $schemas->{$name} or next;
        $body .= "## $name\n\n";
        if (@{ $s->{required} // [] }) {
            $body .= 'Required: ';
            $body .= join(', ', map { "`$_`" } @{ $s->{required} });
            $body .= ".\n\n";
        }
        if (@{ $s->{properties} // [] }) {
            $body .= 'Fields: ';
            $body .= join(', ', map { "`$_`" } @{ $s->{properties} });
            $body .= ".\n\n";
        }
        if (@{ $s->{enum} // [] }) {
            $body .= 'Values: ';
            $body .= join(', ', map { "`$_`" } @{ $s->{enum} });
            $body .= ".\n\n";
        }
    }
    return $body;
}

sub api_overview {
    my ($self) = @_;
    my $p = $self->{parsed};
    my $body = _banner();
    $body .= "# API overview\n\n";
    $body .= "- **Title:** $p->{title} v$p->{version}\n";
    $body .= "- **Base URL:** `$p->{base_url}`\n" if $p->{base_url};
    $body .= "- **Auth:** `Authorization: Bearer arp_live_<token>`\n";
    $body .= "- **Docs:** https://phoenix.arpnetworks.com/api/docs\n";
    $body .= "- **Spec:** `spec/openapi.yaml` (synced by `script/sync-openapi`)\n\n";
    $body .= "## Scopes (set at key creation, immutable)\n\n";
    $body .= "| Scope | Allows |\n";
    $body .= "|-------|--------|\n";
    $body .= "| `read` | GET |\n";
    $body .= "| `write` | server actions, DELETE server, DNS/SSH mutations; includes read |\n";
    $body .= "| `provision` | POST server create; includes write and read |\n\n";
    $body .= "## Rate limits\n\n";
    $body .= "- 120 req/min per client IP (pre-auth)\n";
    $body .= "- 60 req/min per API key (post-auth)\n";
    $body .= "- 429 → `error.type = rate_limited`\n";
    $body .= "- Server create: 7/min per account\n\n";
    $body .= "## Config mapping\n\n";
    $body .= "`~/.config/arpcli/conf`:\n\n";
    $body .= "```ini\n[api]\nbase_url = $p->{base_url}\napi_key = <from dashboard>\n```\n";
    return $body;
}

sub _bandwidth_ranges {
    my ($self) = @_;
    my $schemas = $self->{parsed}{schemas} // {};
    return $schemas->{Bandwidth}{enum} // [];
}

sub _write_file {
    my ($path, $content) = @_;
    make_path(dirname($path));
    open my $fh, '>', $path or die "openapi: cannot write $path: $!\n";
    print {$fh} $content;
    close $fh;
    return;
}

1;